version: '3'

services:
  elasticsearch:
    image: registry.connect.redhat.com/elastic/elasticsearch:8.11.1-63f123cb
    container_name: elasticsearch
    command: >
      bash -c 'if [ x${ELASTIC_PASSWORD} == x ]; then
    echo "Set the ELASTIC_PASSWORD environment variable";
    exit 1;
  elif [ x${KIBANA_PASSWORD} == x ]; then
    echo "Set the KIBANA_PASSWORD environment variable";
    exit 1;
  fi;
  mkdir -p config/certs;
  if [ ! -f config/certs/ca.zip ]; then
    echo "Creating CA";
    podman-compose exec -T elasticsearch \
      bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
    unzip config/certs/ca.zip -d config/certs;
  fi;
  if [ ! -f config/certs/certs.zip ]; then
    echo "Creating certs";
    echo -ne \
    "instances:\n"\
    "  - name: elasticsearch\n"\
    "    dns:\n"\
    "      - elasticsearch\n"\
    > config/certs/instances.yml;
    podman-compose exec -T elasticsearch \
      bin/elasticsearch-certutil cert --silent --pem \
        -out config/certs/certs.zip \
        --in config/certs/instances.yml \
        --ca-cert config/certs/ca/ca.crt \
        --ca-key config/certs/ca/ca.key;
    unzip config/certs/certs.zip -d config/certs;
  fi;
  echo "Setting file permissions";
  podman-compose exec elasticsearch chown -R root:root config/certs;
  podman-compose exec elasticsearch find . -type d -exec chmod 750 {} \;;
  podman-compose exec elasticsearch find . -type f -exec chmod 640 {} \;;
  echo "Waiting for Elasticsearch availability";
  until curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
  echo "Setting kibana_system password";
  until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://localhost:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
  echo "All done!";'
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=W+deOwxFCe2=HsVkRjtC
      - KIBANA_PASSWORD=W+deOwxFCe2=HsVkRjtC
    volumes:
      - /elasticsearch/single-node/data/:/usr/share/elasticsearch/data
      - /elasticsearch/single-node/data/:/usr/share/elasticsearch/logs
      - /etc/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    group: "podman"
    networks:
      - elastic
