version: '3'

services:
  elasticsearch:
    image: registry.connect.redhat.com/elastic/elasticsearch:8.11.1-63f123cb
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=W+deOwxFCeHsVkRjadasdsadtLJASDJADJ
      - KIBANA_PASSWORD=W+deOwxFCe2xxHsVkRjtCJADKJADksjakdj
    volumes:
      - /elasticsearch/single-node/data/:/usr/share/elasticsearch/data
      - /elasticsearch/single-node/logs/:/usr/share/elasticsearch/logs
      - /elasticsearch/single-node/data/certs/:/usr/share/elasticsearch/config/certs
      - /etc/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    command: >
      bash -c '
        echo "ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}"
        echo "KIBANA_PASSWORD: ${KIBANA_PASSWORD}"

        if [ x"${ELASTIC_PASSWORD}" == x ] || [ x"${KIBANA_PASSWORD}" == x ]; then
          echo "Set the ELASTIC_PASSWORD and KIBANA_PASSWORD environment variables"
          exit 1
        fi

        mkdir -p config/certs

        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA"
          /usr/share/elasticsearch/bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip
          unzip config/certs/ca.zip -d config/certs
        fi

        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs"
          echo -ne "instances:\n  - name: elasticsearch\n    dns:\n      - elasticsearch\n" > config/certs/instances.yml
          /usr/share/elasticsearch/bin/elasticsearch-certutil cert --silent --pem \
              -out config/certs/certs.zip \
              --in config/certs/instances.yml \
              --ca-cert config/certs/ca/ca.crt \
              --ca-key config/certs/ca/ca.key

          unzip config/certs/certs.zip -d config/certs
        fi

        echo "Setting file permissions"
        podman exec -it elasticsearch chown -R root:root /usr/share/elasticsearch/config/certs
        podman exec -it elasticsearch find /usr/share/elasticsearch/config/certs -type d -exec chmod 750 {} \;
        podman exec -it elasticsearch find /usr/share/elasticsearch/config/certs -type f -exec chmod 640 {} \;

        echo "Waiting for Elasticsearch availability"
        until curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q "missing authentication credentials"; do
          sleep 30
        done

        echo "Setting kibana_system password"
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://localhost:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do
          sleep 10
        done

        echo "All done!"
      '
    ports:
      - "9200:9200"
      - "9300:9300"
    group: "podman"

networks:
  elastic:
    driver: bridge


[root@dkr-elk-hc01 ELK]# podman logs elasticsearch
ELASTIC_PASSWORD: elastic_password
KIBANA_PASSWORD: kibana_password
Creating CA
Archive:  config/certs/ca.zip
  inflating: config/certs/ca/ca.crt
  inflating: config/certs/ca/ca.key
Creating certs
Archive:  config/certs/certs.zip
   creating: config/certs/elasticsearch/
  inflating: config/certs/elasticsearch/elasticsearch.crt
  inflating: config/certs/elasticsearch/elasticsearch.key
Setting file permissions
chown: changing ownership of 'config/certs/ca/ca.crt': Operation not permitted
chown: changing ownership of 'config/certs/ca/ca.key': Operation not permitted
chown: changing ownership of 'config/certs/ca': Operation not permitted
chown: changing ownership of 'config/certs/ca.zip': Operation not permitted
chown: changing ownership of 'config/certs/instances.yml': Operation not permitted
chown: changing ownership of 'config/certs/certs.zip': Operation not permitted
chown: changing ownership of 'config/certs/elasticsearch/elasticsearch.crt': Operation not permitted
chown: changing ownership of 'config/certs/elasticsearch/elasticsearch.key': Operation not permitted
chown: changing ownership of 'config/certs/elasticsearch': Operation not permitted
chown: changing ownership of 'config/certs': Operation not permitted
chmod: changing permissions of '.': Operation not permitted
chmod: changing permissions of './jdk': Operation not permitted
chmod: changing permissions of './jdk/bin': Operation not permitted
chmod: changing permissions of './jdk/conf': Operation not permitted
chmod: changing permissions of './jdk/conf/management': Operation not permitted
chmod: changing permissions of './jdk/conf/sdp': Operation not permitted
chmod: changing permissions of './jdk/conf/security': Operation not permitted
chmod: changing permissions of './jdk/conf/security/policy': Operation not permitted
chmod:  changing permissions of 

stat /elasticsearch/single-node/data/certs/
  File: /elasticsearch/single-node/data/certs/
  Size: 89              Blocks: 0          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 33598976    Links: 4
Access: (0750/drwxr-x---)  Uid: ( 1000/ elastic)   Gid: ( 1000/ elastic)
Context: unconfined_u:object_r:container_file_t:s0
Access: 2024-01-15 13:31:51.127480446 -0300
Modify: 2024-01-15 13:31:50.695480471 -0300
Change: 2024-01-15 13:31:50.894480459 -0300
 Birth: 2024-01-15 13:18:46.684526464 -0300
